### ISSUE TITLE
Extension error

### ISSUE THREAD

**Issue by cliffordx** [EINDEX/logseq-copilot#1]
I have this error, see screenshot:

<img width="677" alt="Screenshot 2023-02-14 at 10 56 07 AM" src="https://user-images.githubusercontent.com/7141739/218627442-e7eb029d-8b21-4949-9aa4-794c101fe0cc.png">

It is working right now but sometimes it will not show results. I run this alongside other few extensions particularly ChatGPT for Google.

My machine:

MacOS Intel running latest Ventura
Arc browser

**Comment by EINDEX** [comment]
Hey @cliffordx ,

Thanks for try this extension,
I just release [v1.2.0](https://github.com/EINDEX/logseq-copilot/releases/tag/v1.2.0) of this extension, I try chrome with `chatgpt4google` on my machine, which working fine.

Unfortunately I don't have Arc Browser.

Could you retry it again?

**Comment by cliffordx** [comment]
Tested the latest release, so far so good. I will update if I found errors thanks.
