### ISSUE TITLE
Links popup: refs to block/page do not work

### ISSUE THREAD

**Issue by yoyurec** [EINDEX/logseq-copilot#11]
**Describe the bug**
Links clicking do nothing (in popup).
PS: no errors in console.

**To Reproduce**
1. add link to Logseq
2. open url
3. see green dot on pluign icon
4. click on it
5. see popup with logseq results
6. clicking "open block/page" do nothing

**Expected behavior**
links works as in right side inline block and opens Logseq deeplink with page

**Screenshots**
![image](https://user-images.githubusercontent.com/137919/224092440-16b00f89-313c-47ca-9bde-4395ee917663.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome latest
 - Copilot: 1.9.1

**Comment by EINDEX** [comment]
Hello @yoyurec 

Do you set always allow for `chrome-extension://hihgfcgbmnbomabfdbajlbpnacndeihl`?

**Comment by yoyurec** [comment]
issue not about checkbox...
links looks ok, but nothing opened/popuped on click.

![image](https://user-images.githubusercontent.com/137919/224758788-66c8e706-3dd8-4296-9fc2-12d7e4654cbc.png)

**Comment by EINDEX** [comment]
I had switch a new way to open logseq, hope it works

**Comment by yoyurec** [comment]
works just perfect, tnx! 🤩
