### ISSUE TITLE
Performance issue 

### ISSUE THREAD

**Issue by byheaven** [EINDEX/logseq-copilot#12]
**Describe the bug**
After searching in google with logseq-copilot, logseq becomes more and more laggy with the passage of time.

**To Reproduce**
1. Go to google
2. Do some search.
3. Back to logseq and use as usual. Keep logseq open.
4. Input becomes more and more slow.

**Desktop (please complete the following information):**
 - OS:MacOS 13.2.1
 - Browser: chrome 111.0
 - Logseq: 0.8.18
 - Version 1.9.0

**Comment by byheaven** [comment]
Still has the performance issue with the latest nightly build(0325). To reproduce, start a search in chrome and return to logseq. At today's journal page, continuously press the Enter key and there will very likely be a lag (same when pressing backspace). Keeping logseq open for several hours to several days. The lag is getting worse and worse. 

Then I turned of the copilot plugin from chrome and reloaded logseq. The lag disappeared and no performance issues were encountered several days later.

**Comment by saccohuo** [comment]
Same issue, Windows 10.

**Comment by EINDEX** [comment]
Try to reproduce it on my machine, but it is hard to reproduce, for the most of time, Logseq didn't give me any log & information. 

After the v1.10.0 is online, hope this issue will be fixed.

**Comment by EINDEX** [comment]
@saccohuo @byheaven, Did you using some way to sync the graph? iCloud or onedrive?

**Comment by saccohuo** [comment]
> @saccohuo @byheaven, Did you using some way to sync the graph? iCloud or onedrive?

I amusing Dropbox, but the sync method is Logseq original.

**Comment by EINDEX** [comment]
This issue is fixed in 0.9.2 Logseq, you guys can try to upgrade.
@byheaven @saccohuo
