### ISSUE TITLE
Error on Brave Browser "Unknow issues, may you can connect with author."

### ISSUE THREAD

**Issue by 4abhinavjain** [EINDEX/logseq-copilot#13]
Hi,

I tried it on Brave browser [Version 1.49.132 Chromium: 111.0.5563.147 (Official Build) (64-bit)] using Logseq 0.9.1, and it throws this error. The API link opens fine in the browser and a simple token is used. Any suggestions?

**Comment by EINDEX** [comment]
I haven't been using Brave browser, will try it and get back to you soon.

**Comment by EINDEX** [comment]
Do you see the logseq show the success message when you click the below button?
<img width="651" alt="image" src="https://user-images.githubusercontent.com/13883964/230707732-c019e5b3-ff1c-458e-a8b2-2f59c6735c39.png">
 

<img width="372" alt="image" src="https://user-images.githubusercontent.com/13883964/230707717-b4bada39-824b-4cd8-93e1-3ed63d1c30e4.png">

**Comment by 4abhinavjain** [comment]
Unfortunately, it doesn't.
![image](https://user-images.githubusercontent.com/34500467/230708645-30494ff2-05af-47a8-a923-7d5963aa6b90.png)

Although the API engine is starting just fine in logseq application 
![image](https://user-images.githubusercontent.com/34500467/230708739-ee616675-5df5-465c-8676-8a33b78da782.png)

**Comment by EINDEX** [comment]
Oh, you can remove the `/` at the end of Logseq Host. 
I will create patch for this.

**Comment by EINDEX** [comment]
Close this, we have #17 to enhance options and user guide.
