### ISSUE TITLE
{{url}} and {{title}} is undefined

### ISSUE THREAD

**Issue by jinliu** [EINDEX/logseq-copilot#15]
**Describe the bug**
Clicking on the quick capture icon often results in {{url}} and {{title}} expands to 'undefined'.

**To Reproduce**
1. Open Firefox or Vivaldi.
2. Open a new tab and go to some website.
3. Select some text and click on the quick capture popup.
4. Switch to logseq and check the capture.
5. Note: Url and title are 'undefined'
6. Now switch to the browser
7. Click on the logseq copilot extension icon on the toolbar.
8. Now quick capture again.
9. Note: Url and title filled.

**Expected behavior**
Url and title always filled.

**Desktop (please complete the following information):**
 - OS: archlinux
 - Browser: Firefox 112.0, Vivaldi 5.7.2921.65

**Additional context**
This can be fixed by adding 'tabs' permission to manifest.json.
As explained in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#api_permissions
you need this permission for tabs.url and tabs.title.

And as in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#activetab_permission
you can read the url and title of the active tab, but only after the user clicks the extension icon.

**Comment by EINDEX** [comment]
This is interesting, I never thought that Behaver will have differences between Chrome and Firefox.

And, Thanks for sharing this.

Setting this as top priority, will fix it soon.

**Comment by EINDEX** [comment]
Intersting, I was try chrome and firefox on my machine, both working fine.

```json
{
  "version": "1.10.11",
  "author": "eindex.lee@gmail.com",
  "name": "Logseq Copilot",
  "description": "Logseq Copilot, Connect with you logseq API server, bring your information when you browsing.",
  "chrome_url_overrides": {},
  "icons": {
    "192": "assets/img/logo-192.png"
  },
  "content_scripts": [
    {
      "matches": [
        "http://*/*",
        "https://*/*",
        "<all_urls>"
      ],
      "js": [
        "content-script.js"
      ],
      "css": [
        "content-script.css"
      ]
    }
  ],
  "permissions": [
    "storage",
    "activeTab",
    "contextMenus"
  ],
  "options_ui": {
    "page": "options.html",
    "browser_style": false,
    "open_in_tab": true
  },
  "manifest_version": 2,
  "background": {
    "scripts": [
      "background.js"
    ]
  },
  "web_accessible_resources": [
    "content-script.css",
    "assets/img/logo.png"
  ],
  "browser_action": {
    "default_popup": "popup.html",
    "default_title": "Logseq Copilot"
  },
  "browser_specific_settings": {
    "gecko": {
      "id": "{dbe73d0a-f6b8-474a-ad39-0d46a07e4525}"
    }
  }
}
```

**Comment by EINDEX** [comment]
I add permission back.
