### ISSUE TITLE
Refine the error message in Options page when can't connect to Logseq

### ISSUE THREAD

**Issue by jinliu** [EINDEX/logseq-copilot#19]
Currently when clicking the connect button and it fails, the error message is "Unknow issues, may you can connect with author".

1. Should be "Unknown issues. Maybe you can contact with the author.".

2. More importantly, most often this error is because Logseq is not running, or the API Server is not started. So, instead of "contact with the author", we should prompt the user to check these first. E.g. :
```
[Connection failed] (button)
(text) Can't connect to the Logseq API Server. Please check that:
  1. Logseq is running.
  2. Logseq API Server is started. ((link)Guide)
  3. The Logseq host and token entered above are correct. 
```

3. API Server doesn't need Developer Mode in the latest Logseq, so the setup guide should be changed accordingly.

**Comment by jinliu** [comment]
Oh, I see you are redoing the options page: https://github.com/EINDEX/logseq-copilot/issues/17
Nevermind.

**Comment by EINDEX** [comment]
Wow, thanks for sharing!
