### ISSUE TITLE
Feat: show that page URL is in Logseq DB

### ISSUE THREAD

**Issue by yoyurec** [EINDEX/logseq-copilot#2]
Feature request: 
would be cool to show on the icon, that the current page URL is already somewhere in the page content?
(maybe with popup showing results pages list....)
aka "hey man, it's bookmarked/visited in your PKM!" 💡
like https://github.com/karlicoss/promnesia do

![image](https://user-images.githubusercontent.com/137919/218688728-ba38581e-51bc-49da-83d1-6fc149eb98b3.png)

**Comment by EINDEX** [comment]
Hi @yoyurec 

I am doing some research work on this.

Sharing some good news, the spike result is petty nice.

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/13883964/222766253-6533160b-7ffe-4758-b131-5a75abb228a8.png">

I am going to enhance some user experience and style then this feature will release.

**Comment by yoyurec** [comment]
coooool!!!! 🔥🔥🤗
will it search for md links `[title](http://dfdfdfdf)`, or also as plain text URLs `http://dfdfdfdf`?

PS: do you need styling help?

**Comment by EINDEX** [comment]
Just searching the plain text URL， that also support org users.

**Comment by yoyurec** [comment]
> Just searching the plain text URL， that also support org users.

awesome, cose Promnesia do not ((( only Md/Org links

**Comment by EINDEX** [comment]
This feature was published today, wait some time to let the extension/add-on store approve it.

Now the popup can recall org-mode data, but I guess it will render to strange result.
Cause the extension now supports the markdown render pipeline.

**Comment by yoyurec** [comment]
will it shows only on "popup" or on icon too?
![image](https://user-images.githubusercontent.com/137919/223580840-592c20d7-b5ff-4ad6-8265-2879adfe3507.png)

**Comment by EINDEX** [comment]
Yes. 
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/13883964/223612617-5cdf4bd1-599e-4614-8084-2f82d58f6e7e.png">

**Comment by yoyurec** [comment]
OMG!!! 🚀😎🤯🙌
