### ISSUE TITLE
Badge is missing in Firefox

### ISSUE THREAD

**Issue by jinliu** [EINDEX/logseq-copilot#20]
The extension icon's badge is missing in Firefox.

Debugging the extension shows this error:

Uncaught (in promise) TypeError: import_webextension_polyfill2.default.action is undefined
    setExtensionBadge moz-extension://d7aec16b-630f-43c4-bd8c-f65d7dfc7020/background.js:8972
    badgeSearch moz-extension://d7aec16b-630f-43c4-bd8c-f65d7dfc7020/background.js:10674

This is because Browser.action requires manifest v3 (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/action), but for Firefox we use v2 (I suppose because Firefox doesn't support v3 background service worker?).

Possible solution:
Call Browser.browserAction instead (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction)

**Comment by EINDEX** [comment]
Firefox 109 supports V3.

And Logseq Copilot Firefox users are using 110 to 112, only 1 using version 92.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/13883964/233772168-846ad4b6-8882-47f2-af4b-edf9d774136f.png">

I think is suit to upgrade to V3.


 https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/

**Comment by EINDEX** [comment]
fix it at v1.10.20
