### ISSUE TITLE
Cannot work in some cases.

### ISSUE THREAD

**Issue by leeyaunlong** [EINDEX/logseq-copilot#22]
When I open many tabs in the chrome, after 5 mins or more,the copilot cannot work
( click or shortcut trigger the save action, the logseq has no add anything)
At this time , the copilot's setting show the connection is good.
i try to re-connect the logseq again, show message is connected. 
But the webpage still cannot save content to logseq.
Need to refresh the page, ( in sometime, refresh also cannot work)

**Comment by EINDEX** [comment]
How many pages your created? Could you share reproduce methods by step and step.

**Comment by EINDEX** [comment]
The clip flow is below.
![image](https://user-images.githubusercontent.com/13883964/234815451-bb8769d7-bd9f-492c-af06-30aa07bab9ba.png)

Those colors line means two different methods.


The issue you mention here, most is the connection is not established, which means the connection between Current Page(content script) and Background JS is broken.

So, there are two locations that can collect error log.

1. The console for the current page, this part can check the content script's working status.
     you can open it with `F12` or `Ctrl + Art + I`.
2. The other part is checking the extensions page. chrome://extensions/ and open the developer mode. then you will see the service worker here. click it you can see the log for the background part.
![image](https://user-images.githubusercontent.com/13883964/234811718-ae72961c-e3b4-4bd5-9b72-3bfae787aae7.png)

Hope this will help.

**Comment by leeyaunlong** [comment]
the failed log, the logseq api is good at this time.
![snap_20230428_104228_chrome](https://user-images.githubusercontent.com/19405648/235042710-192194a3-c35b-4739-a5ff-b4762e8c1213.png)

**Comment by EINDEX** [comment]
> the failed log, the logseq api is good at this time. ![snap_20230428_104228_chrome](https://user-images.githubusercontent.com/19405648/235042710-192194a3-c35b-4739-a5ff-b4762e8c1213.png)

Yes, this is the connection issue between Background and Tab, Let me try to change another way to connect.

**Comment by EINDEX** [comment]
Fix version just release v1.11.1, if this issue still exists, please reopen.
