### ISSUE TITLE
“Token not currect, Please checking your Logseq Authorization Setting

### ISSUE THREAD

**Issue by DutchPete** [EINDEX/logseq-copilot#23]
This is what my authorization setting looks like:

![image](https://user-images.githubusercontent.com/10794265/235742660-2acf52a7-9fb6-4d9a-85ea-6a68684480b7.png)

This is as per your instructions. What am I doing wrong?

**Comment by EINDEX** [comment]
Hey @DutchPete  

What is the options in your browser, what browser you are using, what version of logseq copilot you are using?

**Comment by EINDEX** [comment]
Logseq Market? I release this on the Chrome web store Edge Add-ons and Firefox add-ons.

Below is the image of the options page.
<img width="942" alt="image" src="https://user-images.githubusercontent.com/13883964/236169677-b9796bf7-1e92-47a5-ac26-2adeec8e4a38.png">

At the search engine pages which copilot support like  [Bing](https://www.bing.com/search?q=tests&qs=n&form=QBRE&sp=-1&ghc=1&lq=0&pq=tes&sc=10-3&sk=&cvid=C2F64D5BA293421B9134477C7E338F84&ghsh=0&ghacc=0&ghpl=)

You can see the config of the copilot.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/13883964/236170559-4cbd4453-523c-4823-be4f-2216b88e2dcc.png">


If you can see the options page, fill `token` in Authorization Token. then it should working fine.

**Comment by EINDEX** [comment]
And this is the reason #17 is in the plan.

**Comment by DutchPete** [comment]
Oops, sorry, my mistake, I did install it from the Chrome Web Store.
I now got it connected 🥳

From what I understand, I can now access Logseq from my browser. The big questions:
- how do I do that?
- how does the clipper work?

My apologies for dumb questions, I am a Logseq newbie.

**Comment by EINDEX** [comment]
No worries, that hints to me should hurry up for #17.

`how do I do that?`
Do clip? when you search keywords on search engine, it will search your logseq graph 

`how does the clipper work?`
right click menus or shortcut, and if you want to enable the float button, you can enable it at options.

**Comment by EINDEX** [comment]
Close this, since the main issues were fixed.
