### ISSUE TITLE
DuckDuckGo dark theme is unreadable

### ISSUE THREAD

**Issue by thinkh** [EINDEX/logseq-copilot#24]
**Describe the bug**

When using the DuckDuckGo dark theme some parts of the copilot sidebar are unreadable. 

**To Reproduce**
1. Go to [DuckDuckGo](https://ddg.gg)
2. Switch to dark theme in settings
3. Search for something that is available in the local graph
4. See result

**Expected behavior**

The colors should have a better contrast in the dark theme.

**Screenshots**

**Default white theme**

![grafik](https://user-images.githubusercontent.com/5851088/235775224-40140cf8-0be9-4c14-8244-3a35c0b1266e.png)

Switch to dark theme

![grafik](https://user-images.githubusercontent.com/5851088/235775589-d4f5fc57-462d-4b6b-bc6f-3f9292c27abb.png)

**Dark theme**

![grafik](https://user-images.githubusercontent.com/5851088/235775773-ec657818-bd6e-4bd4-90c2-2df6c9a71c04.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 112

**Comment by howarddo2208** [comment]
I suspect the tailwind doesn't recognize theme change, but upon trying to fiddle with the code, I ran to an issue with the build script. Do you know how to resolve this @EINDEX ?
```
> logseq-copliot@1.6.0 build
> node build.mjs

/Users/tanhopdo/Developments/opensource/logseq-copilot/src/manifest.json.cjs:28
    version: process.env.VERSION.replace('v', ''),
                                 ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at build (/Users/tanhopdo/Developments/opensource/logseq-copilot/src/manifest.json.cjs:28:34)
    at build (file:///Users/tanhopdo/Developments/opensource/logseq-copilot/build.mjs:96:20)

Node.js v18.16.0
```

**Comment by EINDEX** [comment]
Sorry those days were busy with work, you have to set env var before build.

@howarddo2208 
```bash
export VERSION=v0.0.0
```

**Comment by EINDEX** [comment]
I force the font color for dark and light modes, which will suit for system's default theme.
If change theme at search engine, may can not using the correct theme.

**Comment by howarddo2208** [comment]
Yeah, it doesn't update based on the site. But turns out the problem is actually from the body style, other search sites update the body {color} when changing the theme and the extension inherit it, but it is not the case for duckduckgo

**Comment by howarddo2208** [comment]
now you fixed the issue by hard-code the text color, but then the light theme on all sites is unreadable @EINDEX.
![image](https://user-images.githubusercontent.com/62332195/236636663-861c2e68-081c-4ba4-a560-abbffce3361d.png)
Please consider my PR #26 . Btw, I tested the tailwind, it never switches to dark tho, so I think all the `dark:` styles are not used.

**Comment by EINDEX** [comment]
@howarddo2208  your solutions are awesome, thanks.
