### ISSUE TITLE
Use an indented block for the content in the Clip Template

### ISSUE THREAD

**Issue by aidfulAI** [EINDEX/logseq-copilot#25]
**Problem:**
The default Clip Template pastes everything in one block inside Logseq.

**Solution:**
I would like to add the title in the first block, followed by an indented child block to make it foldable and more structured inside Logseg.

Example: 
![image](https://user-images.githubusercontent.com/113003545/235834290-8c862a52-817f-4652-8c70-ec798c963fdb.png)

**Alternative:**
If this is already possible, it would be good to add it in the "available params" below the template window as a hint how to do it.

**Sidenote**
If I understand you right, than the following screenshot of the website describes this feature:
![image](https://user-images.githubusercontent.com/113003545/235834448-f85b23f1-270f-4c68-9d56-c745a1d22413.png)

I propose a rewrite for more clarity. My suggestions:
**Quick capture** Send webpage info, including URL, title, and text selection to your Logseq graph.
**Quick capture** Save webpage info, including URL and title, to Logseq. Optionally, include the current text selection.

P.S.: Thanks for the work and effort you put into creating this plugin. 👏

**Comment by EINDEX** [comment]
Yes, you are right, this is possible.

This depends on the subblock feature.

**Comment by aidfulAI** [comment]
Can you provide guidance how to do it? What do I have to write in the "clip template" field to create a subblock?

**Comment by EINDEX** [comment]
For now, just have a trick method to archive that.

You can using below template:
```
[[{{date}}]] **{{time}}**
url:: [{{title}}]({{url}})
tags:: [[Clip]]
  - {{content}}
```
You will see some warning showing up, after re-index, everything will render nice.
<img width="1009" alt="image" src="https://github.com/EINDEX/logseq-copilot/assets/13883964/419e9997-35dd-4930-8601-cc37bffc5eed">

**Comment by EINDEX** [comment]
For the subblock feature, just starting thinking how to archive that elegantly. That needs some time to spike and design.

**Comment by aidfulAI** [comment]
Awesome, I was not aware that re-indexing fixes nested lists. Thanks for sharing this as a response.
As you state, it is not super elegant, but works! 👏
