### ISSUE TITLE
Render video in Graph out

### ISSUE THREAD

**Issue by oshliaer** [EINDEX/logseq-copilot#29]
Wow! I see YT tags render!

That's cool!

Is this intended behavior? How can I improve my markup to make this work?

![1683827351222](https://github.com/EINDEX/logseq-copilot/assets/5027939/3bc543a1-068d-4a40-a657-454c3a6ad29f)

**Comment by EINDEX** [comment]
No this not intend. 😢 
I will try to see it can render or not. If not will disable it.

**Comment by EINDEX** [comment]
There 2 reasons for the render not correct:
1. https://github.com/logseq/logseq/issues/9608
 2. not limit the width of the iframe.

**Comment by EINDEX** [comment]
Now, the search interface can render iframe correctly. 
But the `{{video ...}}` is still not rendered.
