### ISSUE TITLE
Add SearX engine and extend to all instances

### ISSUE THREAD

**Issue by krillin666** [EINDEX/logseq-copilot#3]
Hi !
This extension is really useful, even more because it uses Logseq API !
Was wondering if you could extend the search engines to cover SearX and all of its instances, or at least let the user define which instances they want to use from https://searx.space/

Thank you!

**Comment by EINDEX** [comment]
Well, Extending to more search engines was in the plan.

I don't know those before, will try to support them.

**Comment by EINDEX** [comment]
@krillin666 need time to waiting review for Chrome Web Store and Edge Add-ons version.
