### ISSUE TITLE
Results from Copilot not displaying when searching with Bing

### ISSUE THREAD

**Issue by GPS-Nic** [EINDEX/logseq-copilot#36]
**Describe the bug**
The cell shows up for Logseq-Copilot, including the link to the project web page and the feedback button, but none of the results of the search display inside the frame.

**To Reproduce**
1. Go to bing.com
2. Search for a text string you know exists in your Logseq graph
3. View the Logseq-Copilot panel/sidebar
4. See no results

**Expected behavior**
The Copilot sidebar should include relevant entries from the Logseq graph

**Screenshots**
Here's a screenshot from Bing showing the missing entries:
![image](https://github.com/EINDEX/logseq-copilot/assets/102177233/c1507052-24be-4134-97d0-7c8ebf9e4d75)
and here's the same search conducted in Google with the entries displayed correctly:
![image](https://github.com/EINDEX/logseq-copilot/assets/102177233/d3f4ed26-23aa-4b86-8a6e-3569bafd9666)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge Dev 117
 - Version: Logseq 0.9.13

**Comment by areur3ady** [comment]
don't work with duckduckgo either

**Comment by EINDEX** [comment]
Just create a fix commit to fix duckduckgo.

But there is strange for fix this functions at bing, I am still digging out the Root Cause.

**Comment by vonHartz** [comment]
Thanks for this nice extension!

startpage.com also does not work atm.

**Comment by EINDEX** [comment]
@vonHartz could you create a feature request ticket for this?

**Comment by EINDEX** [comment]
I think this works on current bing.com
<img width="1232" alt="Screenshot 2024-03-02 at 11 18 39" src="https://github.com/EINDEX/logseq-copilot/assets/13883964/8d34936a-3cd1-4787-93a9-7d72e2638179">
