### ISSUE TITLE
Unchecked runtime.lastError

### ISSUE THREAD

**Issue by dongtsi** [EINDEX/logseq-copilot#38]
Got this error with **Chrome**.  Cannot write (clip) to Logseq, but the query works well.

I tried to reopen PC/chrome/logseq but all of them not work

OS：win10
Logseq：v0.9.13， v0.9.15 

![image](https://github.com/EINDEX/logseq-copilot/assets/43784905/b1b71bd1-f714-4c67-911d-b7c832270810)

**Comment by EINDEX** [comment]
I can't reproduce this issue. Could you provide more detail, or what the HTML content your clip?

**Comment by EINDEX** [comment]
Thanks @mbm-peter for providing core issue at #40

**Comment by EINDEX** [comment]
fixed in v1.12.2
