### ISSUE TITLE
Journale page used as dateformat, stops quickCapture from working

### ISSUE THREAD

**Issue by mbm-peter** [EINDEX/logseq-copilot#40]
In [this code the date format](https://github.com/EINDEX/logseq-copilot/blob/9553bdc17ea4d13558c0ada1b5343ba6358324e4/src/pages/background/index.ts#L63-L72) that is passed is the journalPage name. As it is August now, the first letter is A and this is not a valid character for date formatting.

```
Uncaught (in promise) RangeError: Format string contains an unescaped latin alphabet character `A`
    result moz-extension://7e84ec07-5a40-42f1-a0ae-62fdd0e916a8/background.js:5104
    format moz-extension://7e84ec07-5a40-42f1-a0ae-62fdd0e916a8/background.js:5085
    blockRending moz-extension://7e84ec07-5a40-42f1-a0ae-62fdd0e916a8/background.js:8548
    quickCapture moz-extension://7e84ec07-5a40-42f1-a0ae-62fdd0e916a8/background.js:8621
    async* moz-extension://7e84ec07-5a40-42f1-a0ae-62fdd0e916a8/background.js:8592
```

**Comment by EINDEX** [comment]
This issue seems to be the core reason for #38 . migrate to that issue, and thanks for your information.
