### ISSUE TITLE
Feature: Implement send tabs to logseq / restore

### ISSUE THREAD

**Issue by poelzi** [EINDEX/logseq-copilot#47]
**Is your feature request related to a problem? Please describe.**
We could use logseq to manage groups of tabs/ontab but combined with logseq.
This way, we could structure our research to topics in logseq, but also hybernate the accompaning browser window with it.

**Describe the solution you'd like**
* Each Window has a Topic, which correspons to the page in logseq. Can be set in the extension window.

* Add a Button: `Suspend to logseq` (with warning please ;)
  This adds/edits the page with a  special block that links to all the tabs and to the session id that is used to hybernate the window. Like a real session manager does, with forms etc

In logseq we need a plugin:
* The block gets rendered with a button `resume session`.
   This opens a new browser window with all tabs restored.

**Comment by EINDEX** [comment]
I think [OneTab](https://chromewebstore.google.com/detail/onetab/chphlpgkkbolifaimnlloiipkdnihall) extension can take care of suspend & resume wisely.

In my imaging, logseq-copilot should help you save the highlights and comments to logseq and bring that knowledge back to the browser.

What's do you think about this?

**Comment by EINDEX** [comment]
Close for no response.
