### ISSUE TITLE
Add Clip page link button to menu of button extension

### ISSUE THREAD

**Issue by JosefJezek** [EINDEX/logseq-copilot#50]
Could you add "Clip page link" button to menu of button extension?

![image](https://github.com/EINDEX/logseq-copilot/assets/2110319/9f4f0adb-39d2-4745-8a5d-ba5a5c7734ea)

I need this button for pages with a custom right-click context menu and blocking shortcuts, ex. Google Docs.

**Comment by EINDEX** [comment]
you can using the shortcut `Ctrl/Cmd + Shift + U`.
