### ISSUE TITLE
"To block" link throwing error when opening in Logseq

### ISSUE THREAD

**Issue by thelazyoxymoron** [EINDEX/logseq-copilot#56]
**Describe the bug**
When I click on "To block" and try to open this in logseq, getting following error:
<img width="420" alt="Screenshot 2024-01-08 at 3 03 25 PM" src="https://github.com/EINDEX/logseq-copilot/assets/9106868/1fa502e9-9b8c-4894-a346-a9cad8716e15">

The full URL is: `logseq://graph/?block-id=659bc102-9e4c-4892-925b-c473b9ce5911`

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.2.1
 - Browser: Firefox 121.0
 - Logseq-copilot: 1.13.0

**Comment by EINDEX** [comment]
Thanks for notity! I add a quick patch to fixing this issue.

**Comment by EINDEX** [comment]
Avaliable on Firefox store now.

**Comment by thelazyoxymoron** [comment]
Sorry to report that this is still not fixed. Using the updated 0.13.1 version and still getting this issue.

**Comment by EINDEX** [comment]
I made a mistake, missing a commit in version `v1.13.1`, release a new version in `v1.13.2` for this. It good for now.

**Comment by thelazyoxymoron** [comment]
Thanks!
