### ISSUE TITLE
[Feature request] User adjustable debounce timer on floating button.

### ISSUE THREAD

**Issue by winneratwin** [EINDEX/logseq-copilot#58]
**Is your feature request related to a problem? Please describe.**
I was wondering why i couldn't clip the content using the floating button unless i double click the button, so i went into the source code and found out that there was a debounce timer in QuickCapture.tsx with 100ms, finding that i tried clicking just once super fast and then it works.

**Describe the solution you'd like**
I would love to see an option to adjust the debounce timer because the default behavior imo seems like a bug, since when you click for not even a long duration such as a quarter second/half a second of hold time the button pops up next to your cursor and there is no feedback to the user that they were too slow, leading to them trying to click at the same speed again leading to the button going to the bottom right the more the user clicks it.

**Describe alternatives you've considered**
You could also raise the debounce timer to 250ms instead of the 100ms as it is right now, or remove the debounce entirely.

**Additional context**
First time user here and this behavior threw me off and i thought the extension was bugged and the button wasn't listening to inputs due to me using firefox and not chrome since that is the most popular browser.

**Comment by EINDEX** [comment]
Hey, winneratwin

I made a fix in v1.14.1, upgrade logic, and removed debounce, please check this version.
