### ISSUE TITLE
FR: Highlight the search term in the results.

### ISSUE THREAD

**Issue by byheaven** [EINDEX/logseq-copilot#6]
If the results are long, it's hard to find the keywords. Thank you!

**Comment by EINDEX** [comment]
Highlight information should provider by logseq side. 

I will try enable on there side, then continue on our side.

**Comment by EINDEX** [comment]
Create an issue at Logseq. https://github.com/logseq/logseq/issues/8881

**Comment by EINDEX** [comment]
Highlight added at [v1.10.0](https://github.com/EINDEX/logseq-copilot/releases/tag/v1.10.0).
now is under view.
