### ISSUE TITLE
Unable to clip unless the "Display Floating Button" is turned on

### ISSUE THREAD

**Issue by ShrimpyChips** [EINDEX/logseq-copilot#61]
**Describe the bug**
A bug seems to have just developed for me starting today. I was unable to clip anything on both my work PC and my home PC. Logseq Copilot would show that it was connected to the API and would even show result in the google search results page but any attempt to clip a link would result in no errors but nothing would show up in Logseq. After playing around with things trying to find the issue I found out that I could resolve the issue and get it to clip if I turned on the "Display Floating Button" function. The weirder thing is that this also dosn't seem to actually show any floating button (something I didn't want anyways).

So this is solved for me, at least for now, as I'm getting the functionality that I'm looking for. But figured I would post the bug since it seems counter to expected results and in case it helps anyone else with the same issue.

**To Reproduce**
To cause the bug have "Display Floating Button" turned off, to apply the workaround turn it on.

**Expected behavior**
To have clipping function without the "Display Floating Button" turned on.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: v1.14.1

**Comment by EINDEX** [comment]
Fixed this in v1.14.2 version
