### ISSUE TITLE
Unable to clip selected text with Logseq 0.10.7 on Firefox

### ISSUE THREAD

**Issue by thelazyoxymoron** [EINDEX/logseq-copilot#62]
**Describe the bug**
I have enabled "Display floating button" and tried to select a text on a webpage and click on the floating button, but nothing gets captured. This used to work fine with earlier versions of both Logseq and the extension.

**To Reproduce**
1. Select some text on a webpage (e.g. wikipedia)
2. Click on the floating button to capture
3. Should get captured in Logseq but nothing happens

**Expected behavior**
It should copy the text into the journal (or page, depending upon the setting)

**Screenshots**
<img width="920" alt="Screenshot 2024-03-01 at 3 04 48 PM" src="https://github.com/EINDEX/logseq-copilot/assets/9106868/334da8e0-4241-4bf6-a5c4-e9b691543d6a">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox 123.0
 - Version: 1.14.1

**Comment by EINDEX** [comment]
dup with #61

**Comment by EINDEX** [comment]
Fixed this in v1.14.2 version

**Comment by thelazyoxymoron** [comment]
Updated and I still see this issue.

**Comment by EINDEX** [comment]
This is strange

**Comment by EINDEX** [comment]
But it works well on Wikipedia.
<img width="1750" alt="Screenshot 2024-03-02 at 22 43 58" src="https://github.com/EINDEX/logseq-copilot/assets/13883964/dea671ab-3bee-4a72-8c73-fed1b829a16b">

**Comment by thelazyoxymoron** [comment]
Unfortunately this is not working for me on Wikipedia as well. I tried this on Chrome though and everything works correctly. I'm getting this error on Firefox:

![Screenshot 2024-03-04 at 1 11 29 PM](https://github.com/EINDEX/logseq-copilot/assets/9106868/1156e0ec-b6d1-4b42-8be1-5cafbc78665b)

**Comment by EINDEX** [comment]
Close for fixed at `v1.14.3` commit 3e931db.
