### ISSUE TITLE
Results don't get shown on page, only in popup

### ISSUE THREAD

**Issue by aadilayub** [EINDEX/logseq-copilot#63]
When I search for something on any search engine, the logseq search results don't show up on the page, only a large button saying "Config it". Whereas when I click on the extension badge, it shows the same results just fine.

![image](https://github.com/EINDEX/logseq-copilot/assets/31581044/d614a721-f1e0-4b2e-96e1-98a7341e2630)

I've reproduced this issue multiple times on multiple search engines, and have enabled all permissions for the extension.

**Comment by aadilayub** [comment]
The extension service worker devtools show a bunch of errors:

![image](https://github.com/EINDEX/logseq-copilot/assets/31581044/25d4bfcf-8d2c-44a1-a079-5fd4b243c85d)

**Comment by aadilayub** [comment]
Looks like this issue went away after restarting the browser.

**Comment by NexZhu** [comment]
Same problem, restarting the browser didn't help

**Comment by EINDEX** [comment]
@NexZhu @aadilayub Does this issue still exist?

**Comment by aadilayub** [comment]
this is fixed for me!

**Comment by EINDEX** [comment]
Thanks!
