### ISSUE TITLE
Margin -8px clipping the text at the top

### ISSUE THREAD

**Issue by AnweshGangula** [EINDEX/logseq-copilot#64]
**Describe the bug**
The current code has a margin of `-8px` for  `copilotBody` class which is causing the top most div to be clipped. Check the screenshot below.

It might be an issue with my browser. I'm using 
- **Browser:** 
- **OS:** Windows

**Screenshots**
![image](https://github.com/EINDEX/logseq-copilot/assets/22996896/f6f2784d-6c6a-4ceb-bb87-679541ecf9e5)

**Desktop:**
 - **OS:** Windows
 - **Browser:** Microsoft Edge - Version 122.0.2365.92 (Official build) (64-bit)
 - **Extension Version:** v1.14.3
 - **Logseq Version:** v0.10.7!

**Comment by EINDEX** [comment]
I thought your new style code should fix this issue! which will be released at v1.15.0! 
Thanks!
