### ISSUE TITLE
I can't find the start server button. Your README is incomplete :(

### ISSUE THREAD

**Issue by galihlprakoso** [EINDEX/logseq-copilot#65]
**Describe the bug**
I tried to follow steps on your readme, and found the Usage section. I was able to `Enable HTTP APIs Server`. But I can't found this menu anywhere else on my Logseq app.
<img width="497" alt="Screen Shot 2024-04-03 at 06 19 14" src="https://github.com/EINDEX/logseq-copilot/assets/16918033/35ffa0eb-0240-4bfd-b8c9-1d752c18b799">

Where is it?

**Comment by galihlprakoso** [comment]
Never mind. I was able to start server by following this more complete instruction:
- https://docs.logseq.com/#/page/local%20http%20server?anchor=ls-block-66053e50-b97d-43e6-ad64-27ed06a624f2

**Comment by EINDEX** [comment]
btw pr welcome, I need work to feeding my family, not a full time open source worker.
