### ISSUE TITLE
Safari Extension

### ISSUE THREAD

**Issue by ssuds** [EINDEX/logseq-copilot#72]
**Is your feature request related to a problem? Please describe.**
I'm primarily a Safari user - this extension seems excellent but is primarily supported by Chrome, Firefox and Edge which I don't use

**Describe the solution you'd like**
An officially supported safari extension would be great!

**Describe alternatives you've considered**
I can recompile the extension for Safari myself following these instructions: https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari/
However, I wanted to reach out and see if there was a specific reason that there isn't an official Safari version of this extension available before going down that rabbit hole.

Thank you!

**Comment by EINDEX** [comment]
Hi @ssuds,

To create a Safari extension, which have to register Apple developer program.
which cost 99 USD pre year, That is too much for this Non-Profit open source extension.

If you want to sponsor this, I will try and make this happen.

https://developer.apple.com/support/enrollment/#:~:text=Completing%20your%20enrollment&text=The%20Apple%20Developer%20Program%20annual,in%20local%20currency%20where%20available.

**Comment by ssuds** [comment]
Hey there - totally understand and that is super frustrating on Apple's part. Noted on the sponsorship and I will reach out down the line if that ever makes sense. Thank you very much for the context!
