### ISSUE TITLE
Navigation to block and quickcapture not working under Firefox

### ISSUE THREAD

**Issue by krillin666** [EINDEX/logseq-copilot#9]
Whenever I click on a `to bloc`k, or try to add a quick capture, I see this error in the logs: `Prevented Nativation to ... due to an unknown protocol.`

**Comment by EINDEX** [comment]
Oh, could you share the link with me? 

You can copy the link via right-click. it will give you some thing like the below.

`logseq://graph/logseq?block-id=64047d32-e312-4be0-b827-1a8dbb057e9c`
